"use client";
import {useId,useState} from 'react';
import {Check,ChevronDown,Search,X} from 'lucide-react';
import type {Meta} from '@/lib/ui-types';
type Props={title:string;name:string;items:Meta[];selected:string[];onChange:(ids:string[])=>void;description:string;className?:string;unavailable?:Record<string,string[]>;checking?:boolean};
export default function CatalogPicker({title,name,items,selected,onChange,description,className='',unavailable={},checking=false}:Props){
 const [query,setQuery]=useState('');const id=useId();const matches=items.filter(item=>item.name?.toLocaleLowerCase('es').includes(query.trim().toLocaleLowerCase('es')));
 const toggle=(value:string,checked:boolean)=>onChange(checked?[...new Set([...selected,value])]:selected.filter(v=>v!==value));
 return <fieldset className={`catalog-picker full-width ${className}`}><legend>{title}</legend><p className="form-note">{description}</p>{selected.map(value=><input key={value} type="hidden" name={name} value={value}/>)}<div className="selection-chips" aria-label={`${title} seleccionados`}>{selected.map(value=>{const item=items.find(i=>i.id===value);return <span className={unavailable[value]?.length?'selection-chip has-conflict':'selection-chip'} key={value}>{item?.name||'Registro no disponible'}<button type="button" aria-label={`Quitar ${item?.name||'selección'}`} onClick={()=>toggle(value,false)}><X size={13}/></button></span>;})}{!selected.length&&<small>Ninguno seleccionado</small>}</div><details className="catalog-options"><summary><span>{selected.length?`${selected.length} seleccionado${selected.length===1?'':'s'}`:'Seleccionar del catálogo'}</span><ChevronDown size={16}/></summary><div className="catalog-search"><Search size={16}/><label className="sr-only" htmlFor={id}>Buscar {title.toLocaleLowerCase('es')}</label><input id={id} type="search" placeholder="Buscar por nombre…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="catalog-option-list">{matches.map(item=><label className="catalog-option" key={item.id}><input type="checkbox" name={`${name}Choice`} value={item.id} checked={selected.includes(item.id)} disabled={checking||!!unavailable[item.id]?.length&&!selected.includes(item.id)} onChange={e=>toggle(item.id,e.target.checked)}/><span>{item.name}{!!unavailable[item.id]?.length&&<small>No disponible: {unavailable[item.id].join(', ')}</small>}</span>{selected.includes(item.id)&&<Check size={15}/>}</label>)}{!matches.length&&<p>No hay coincidencias en el catálogo.</p>}</div></details></fieldset>;
}
