"use client";
import {FormEvent,useEffect,useRef,useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {useTutorial} from '@/components/dashboard-tutorial';
import {defaultWeekRanges,nextDay,periodBounds,shortWeekDate,validateWeekRanges,type WeekRange,type CommercialWeek} from '@/lib/commercial-weeks';
type State={weeks:CommercialWeek[];updatedAt:string|null;custom:boolean;closed:boolean};
export default function CommercialWeeks({year,month,isAdmin,refreshKey,onDone}:{year:number;month:number;isAdmin:boolean;refreshKey:number;onDone:()=>Promise<void>}){
 const {active:tutorial}=useTutorial();const [state,setState]=useState<State|null>(null),[draft,setDraft]=useState<WeekRange[]>(()=>defaultWeekRanges({year,month})),[expected,setExpected]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);const dirty=useRef(false);
 useEffect(()=>{const c=new AbortController();setLoading(true);void fetch(`/api/commercial-weeks?year=${year}&month=${month}`,{signal:c.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'No se pudieron cargar las semanas');if(c.signal.aborted)return;setState(data);if(!dirty.current){setDraft(data.weeks);setExpected(data.updatedAt);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[year,month,refreshKey]);
 const bounds=periodBounds({year,month});
 function change(index:number,key:keyof WeekRange,value:string){dirty.current=true;setDraft(rows=>rows.map((r,i)=>i===index?{...r,[key]:value}:r));setNotice('');}
 function add(){const last=draft[draft.length-1];if(!last||last.startDate>=last.endDate)return;const middle=new Date((Date.parse(last.startDate+'T12:00:00Z')+Date.parse(last.endDate+'T12:00:00Z'))/2).toISOString().slice(0,10);dirty.current=true;setDraft([...draft.slice(0,-1),{...last,endDate:middle},{startDate:nextDay(middle),endDate:last.endDate}]);}
 function remove(index:number){dirty.current=true;setDraft(rows=>{if(index===0)return [{...rows[1],startDate:rows[0].startDate},...rows.slice(2)];return rows.flatMap((r,i)=>i===index?[]:i===index-1?[{...r,endDate:rows[index].endDate}]:[r]);});}
 async function save(reset=false){if(!state||busy||tutorial)return;setError('');setNotice('');setBusy(true);try{if(!reset)validateWeekRanges(draft,{year,month});const r=await fetch('/api/commercial-weeks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({year,month,ranges:draft,reset,expectedUpdatedAt:expected})}),data=await r.json();if(!r.ok)throw Error(data.error||'No se pudieron guardar las semanas');dirty.current=false;setState(data);setDraft(data.weeks);setExpected(data.updatedAt);setNotice(reset?'Se restauraron las cuatro semanas habituales.':'Semanas guardadas para todo el equipo.');await onDone();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const submit=(e:FormEvent)=>{e.preventDefault();void save();};
 return <section className="panel commercial-weeks"><div className="section-heading"><div><h2>Semanas del mes</h2><p>Estos períodos se usan en la distribución y el rendimiento semanal de todos los comerciales.</p></div></div>{loading?<p role="status">Cargando semanas…</p>:<div className="week-range-summary">{state?.weeks.map(w=><span key={w.key}>{shortWeekDate(w.startDate)}–{shortWeekDate(w.endDate)}</span>)}</div>}{error&&<p className="error-banner" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{state?.closed&&<p className="form-note">El mes está cerrado. Un administrador debe reabrirlo para cambiar sus semanas.</p>}{isAdmin&&<details className="week-editor"><summary>Configurar semanas <small>Solo administradores</small></summary><form onSubmit={submit}><fieldset disabled={loading||busy||!!state?.closed||!!tutorial}><p className="form-note">Incluye todos los días del mes, sin huecos ni solapamientos. Puedes usar entre una y seis semanas.</p>{draft.map((w,i)=><div className="week-range-row" key={i}><strong>Semana {i+1}</strong><label>Inicio<input name="weekStart" aria-label={`Inicio de semana ${i+1}`} type="date" required min={bounds.first} max={bounds.last} value={w.startDate} onChange={e=>change(i,'startDate',e.target.value)}/></label><label>Fin<input name="weekEnd" aria-label={`Fin de semana ${i+1}`} type="date" required min={bounds.first} max={bounds.last} value={w.endDate} onChange={e=>change(i,'endDate',e.target.value)}/></label><button type="button" className="icon-button danger" aria-label={`Quitar semana ${i+1}`} disabled={draft.length===1} onClick={()=>remove(i)}><Trash2 size={17}/></button></div>)}<button className="btn secondary" type="button" disabled={draft.length>=6||draft[draft.length-1].startDate>=draft[draft.length-1].endDate} onClick={add}><Plus size={16}/>Agregar semana</button><div className="dialog-actions"><button className="btn secondary" type="button" onClick={()=>void save(true)}>Restaurar semanas habituales</button><button className="btn">{busy?'Guardando…':'Guardar semanas'}</button></div></fieldset></form><button className="text-button" disabled={loading||busy||!!tutorial} type="button" onClick={()=>{dirty.current=false;if(state){setDraft(state.weeks);setExpected(state.updatedAt);}setError('');setNotice('Se cargaron las semanas actuales; se descartó el borrador.');}}>Descartar borrador y usar semanas actuales</button></details>}</section>;
}
