"use client";
import {useTutorial} from "@/components/dashboard-tutorial";
import Image from "next/image";
import {FormEvent,useEffect,useState,useRef} from 'react';
import {UserRound,X,Camera} from 'lucide-react';
type Profile={username:string;avatar:string|null;textSize:string;mustChangePassword:boolean};
export default function ProfileSettings(){
 const {active:tutorial}=useTutorial();
 const [user,setUser]=useState<Profile|null>(null),[open,setOpen]=useState(false),[photo,setPhoto]=useState<string|null>(null),[size,setSize]=useState('normal'),[error,setError]=useState(''),[busy,setBusy]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
 function apply(u:Profile){setUser(u);setPhoto(u.avatar);setSize(u.textSize);document.documentElement.dataset.textSize=u.textSize;window.dispatchEvent(new CustomEvent('profile-updated',{detail:u}));}
 useEffect(()=>{void fetch('/api/auth/me').then(r=>r.json()).then(u=>{if(!u.username)return;apply(u);if(u.mustChangePassword)setOpen(true);}).catch(()=>{});},[]);
 useEffect(()=>{if(tutorial?.preview==='profile')setOpen(true);else if(tutorial)setOpen(false);},[tutorial]);
 useEffect(()=>{const node=dialog.current;if(!node)return;if(open){if(tutorial)node.show();else node.showModal();}else node.close();},[open,tutorial]);
 async function selectPhoto(file?:File){if(!file)return;setError('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('Selecciona PNG, JPEG o WebP de hasta 5 MB.');return;}try{const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=canvas.height=256;const side=Math.min(bitmap.width,bitmap.height);canvas.getContext('2d')!.drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,256,256);bitmap.close();setPhoto(canvas.toDataURL('image/jpeg',.82));}catch{setError('No se pudo abrir la foto.');}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||tutorial)return;setBusy(true);setError('');const form=e.currentTarget,f=new FormData(form);try{const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({avatar:photo,textSize:size,...(f.get('password')?{password:f.get('password'),currentPassword:f.get('currentPassword')}:{})})}),data=await r.json();if(!r.ok)throw Error(data.error||'No se pudo guardar');const wasRequired=user?.mustChangePassword;apply(data);form.reset();setOpen(false);if(wasRequired)window.location.assign('/dashboard');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><button type="button" className="profile-trigger" data-tour="profile" aria-label="Mi perfil" title="Mi perfil" onClick={()=>{setError('');setPhoto(user?.avatar||null);setSize(user?.textSize||'normal');setOpen(true);}}>{user?.avatar?<Image unoptimized src={user.avatar} alt="Mi foto de perfil" width={38} height={38}/>:<UserRound size={20}/>}</button>{open&&<dialog ref={dialog} className="dialog profile-dialog" aria-labelledby="profile-title" onCancel={e=>{if(user?.mustChangePassword||busy)e.preventDefault();else setOpen(false);}}><div className="section-heading"><h2 id="profile-title">{user?.mustChangePassword?'Cambia tu contraseña temporal':'Mi perfil'}</h2>{!user?.mustChangePassword&&<button type="button" className="icon-button" aria-label="Cerrar perfil" disabled={busy} onClick={()=>setOpen(false)}><X size={20}/></button>}</div><p>{user?.username}</p>{user?.mustChangePassword&&<p className="form-note">El administrador restableció tu acceso. Elige una contraseña propia para continuar.</p>}<form onSubmit={save}><fieldset disabled={busy} className="profile-fields"><label className="profile-photo"><span className="profile-avatar">{photo?<Image unoptimized src={photo} alt="Vista previa de mi foto" width={88} height={88}/>:<Camera size={32}/>}</span>Foto de perfil<input name="profilePhoto" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void selectPhoto(e.target.files?.[0])}/><small>Hasta 5 MB. Se ajusta a una foto cuadrada.</small></label>{photo&&<button className="text-button" type="button" onClick={()=>setPhoto(null)}>Quitar foto</button>}<label>Tamaño de texto<select name="textSize" value={size} onChange={e=>setSize(e.target.value)}><option value="normal">Normal</option><option value="large">Grande</option><option value="extra">Muy grande</option></select><small>Se guarda para tu cuenta y se aplica en todas las herramientas.</small></label><details open={!!user?.mustChangePassword}><summary>Cambiar contraseña</summary><label>Contraseña actual o temporal<input name="currentPassword" type="password" autoComplete="current-password" required={!!user?.mustChangePassword}/></label><label>Nueva contraseña<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={72} required={!!user?.mustChangePassword}/></label><small>Al menos 12 caracteres. Tus otras sesiones se cerrarán.</small></details>{error&&<p role="alert" className="error-banner">{error}</p>}<div className="dialog-actions"><button className="btn" disabled={!!tutorial}>{busy?'Guardando…':'Guardar preferencias'}</button></div></fieldset></form></dialog>}</>;
}
