"use client";
import { useEffect, useState } from 'react';
type Row={linked?:boolean;entity:string;id:string;label:string;amount:string;date:string;deletedAt:string;expiresAt:string;salesperson:string;course:string};
export default function RecordTrash({onDone,readOnly=false}:{readOnly?:boolean;onDone:()=>Promise<void>}){
 const [rows,setRows]=useState<Row[]>([]),[reload,setReload]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);void fetch('/api/trash',{signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'No se pudo cargar la papelera');setRows(data.rows);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[reload]);
 async function restore(row:Row){setBusy(row.id);setError('');try{const r=await fetch('/api/trash',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entity:row.entity,id:row.id})});const data=await r.json();if(!r.ok)throw Error(data.error||'No se pudo restaurar');setNotice(`${row.label}: registro restaurado.`);setRows(old=>old.filter(x=>x.id!==row.id));await onDone();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <section className="panel trash-panel"><div className="section-heading"><div><h2>Papelera · 7 días</h2><p>Servicios y ventas eliminados dejan de contar en los reportes. Puedes restaurarlos antes del vencimiento indicado; después quedan fuera de recuperación y se eliminan definitivamente en la limpieza automática diaria o al consultar la papelera.</p><p>Administradores: todos los registros. Vendedores: registros de su comercial asignado. La recuperación no reinicia las fechas ni cambia el importe.</p></div><button className="btn secondary" disabled={loading} onClick={()=>{setError('');setReload(n=>n+1);}}>Actualizar papelera</button></div>{error&&<p className="error-banner" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="table-scroll"><table><thead><tr><th>Registro</th><th>Comercial</th><th>Importe</th><th>Fecha original</th><th>Recuperable hasta</th><th>Acción</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.entity}-${row.id}`}><td><strong>{row.label}</strong><small>{row.entity==='SERVICE'?'Servicio':'Certificado'} · {row.course}</small></td><td>{row.salesperson}</td><td>S/ {Number(row.amount).toFixed(2)}</td><td>{row.date.slice(0,10)}</td><td>{new Date(row.expiresAt).toLocaleString('es-PE',{timeZone:'America/Lima'})}</td><td><button className="btn secondary" title={row.linked?"Recupera la venta de certificados vinculada":undefined} disabled={readOnly||row.linked||!!busy||Date.parse(row.expiresAt)<=Date.now()} onClick={()=>void restore(row)}>{busy===row.id?'Restaurando…':'Restaurar'}</button></td></tr>)}</tbody></table></div>{loading?<p role="status">Cargando papelera…</p>:!rows.length&&<p>No hay registros recuperables.</p>}</section>;
}
