"use client";
import RecordProfile from "@/components/record-profile";
import { useEffect, useState } from 'react';
const entityNames: Record<string,string> = { INSTRUCTOR_CONFIRMATION:"Confirmación de instructor", WEEK_PLAN:"Semanas comerciales", QUOTATION: "Cotización", QUOTATION_PDF: "PDF de cotización", MONTH: "Mes", SERVICE:'Servicio', CERTIFICATE:'Certificado', USER:'Usuario', COURSE:'Curso', INSTRUCTOR:'Instructor', SALESPERSON:'Comercial', LOCATION:'Ubicación' };
const actions: Record<string,string> = { CONFIRM:'Jornada confirmada', UNCONFIRM:'Confirmación retirada', PASSWORD_RESET:'Contraseña restablecida', PASSWORD_CHANGE:'Contraseña cambiada', PROFILE_UPDATE:'Perfil actualizado', CREATE:'Creado', UPDATE:'Editado', DELETE:'Eliminado', TRASH:'Enviado a papelera', CLOSE: "Mes cerrado", REOPEN: "Mes reabierto", RESTORE:'Restaurado' };
const labels: Record<string,string> = { confirmed:'Confirmación', date:'Fecha de jornada', ranges:'Semanas', startDate:'Inicio', endDate:'Fin', contact:'Contacto', participants:'Participantes', validUntil:'Vigencia', followUpDate:'Seguimiento', tentativeDates:'Fechas tentativas', conditions:'Condiciones', notes:'Observaciones', convertedAt:'Conversión en servicio', serviceId:'Servicio creado', size:'Tamaño', closedAt:'Fecha de cierre', closedByName:'Administrador del cierre', company:'Empresa', customerName:'Cliente', amount:'Importe', status:'Estado', serviceDate:'Primera fecha', saleDate:'Fecha de venta', invoicedAt:'Fecha de facturación', dates:'Fechas y horarios', certificateKind:'Tipo de certificado', instructors:'Instructores', courses:'Cursos', course:'Curso', instructor:'Instructor', location:'Ubicación', salesperson:'Comercial', correlativeCode:'Correlativo', modality:'Modalidad', travelMode:'Viáticos', certificatesOnly:'Solo certificados', customerType:'Tipo de cliente', deletedAt:'Fecha de eliminación', name:'Nombre', address:'Dirección', dni:'DNI', emoExpiresAt:'Vencimiento EMO', sctr:'SCTR', sctrStartsAt:'Inicio SCTR', sctrEndsAt:'Fin SCTR', carModel:'Modelo del auto', carPlate:'Placa', username:'Correo de acceso', role:'Rol', color:'Color', salespersonId:'Comercial asignado', district:'Distrito', department:'Departamento' };
const vocabulary: Record<string,string> = { PAID:'Pagado', SUPERVISOR:'Supervisor', OPERATOR:'Operador', INSPECTION:'Inspección', DRAFT:'Borrador', SENT:'Enviada', ACCEPTED:'Aceptada', REJECTED:'Rechazada', EXPIRED:'Vencida', SCHEDULED:'Programado', EXECUTED:'Ejecutado', INVOICED:'Facturado', MIXED:'Virtual / Presencial', VIRTUAL:'Virtual', IN_PERSON:'Presencial', NONE:'No aplica', PLANE:'Avión', BUS:'Bus', COMPANY:'Empresa', NATURAL_PERSON:'Persona natural', ADMIN:'Administrador', SALES:'Vendedor' };
const value = (v: unknown): string => v===null || v===undefined ? '—' : typeof v==='boolean' ? v?'Sí':'No' : typeof v==='string' ? vocabulary[v] ?? v : Array.isArray(v) ? v.map(value).join(' · ') : typeof v==='object' ? Object.entries(v).filter(([k])=>!['id','serviceId'].includes(k)).map(([k,x])=>`${labels[k] ?? k}: ${value(x)}`).join(', ') : String(v);
type Log = { id:string; createdAt:string; actorName:string; entity:string; label:string; action:string; before:Record<string,unknown>|null; after:Record<string,unknown>|null };
export default function RecordHistory() {
  const [rows,setRows]=useState<Log[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');void fetch(`/api/history?page=${page}&search=${encodeURIComponent(search)}`,{signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'No se pudo cargar el historial');setRows(data.rows);setTotal(data.total);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[page,search]);
  return <section className="panel history-panel"><div className="section-heading"><div><h2>Historial de cambios</h2><p>Desde la activación de esta función. Los administradores ven todo; los vendedores, su comercial y sus propias acciones.</p></div></div><label className="search-box">Buscar registro<input aria-label="Buscar en historial" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Empresa, cliente o nombre…" /></label>{error&&<p className="error-banner" role="alert">{error}</p>}{loading?<p role="status">Cargando historial…</p>:rows.map(log=>{const keys=Object.keys({...log.before,...log.after}).filter(k=>labels[k]&&(!k.endsWith('Id')||k==='serviceId')&&value(log.before?.[k])!==value(log.after?.[k]));return <details className="history-entry" key={log.id}><summary><strong>{actions[log.action]} · {entityNames[log.entity]} · {log.label}</strong><small>{log.actorName} · {new Date(log.createdAt).toLocaleString('es-PE',{timeZone:'America/Lima'})}</small></summary><RecordProfile entity="HISTORY" recordId={log.id}/><div className="table-scroll"><table><thead><tr><th>Campo</th><th>Antes</th><th>Después</th></tr></thead><tbody>{keys.map(key=><tr key={key}><td>{labels[key]}</td><td>{value(log.before?.[key])}</td><td>{value(log.after?.[key])}</td></tr>)}</tbody></table>{!keys.length&&<p>Acción registrada. Los datos de acceso sensibles no se incluyen.</p>}</div></details>;})}{!loading&&!rows.length&&<p>No hay cambios para esta selección.</p>}<div className="history-pagination"><button className="btn secondary" disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page} · {total} cambios</span><button className="btn secondary" disabled={loading||page*30>=total} onClick={()=>setPage(p=>p+1)}>Siguiente página</button></div></section>;
}
