"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';import Link from 'next/link';import {upload} from '@vercel/blob/client';import {ClipboardList,LogOut,RefreshCw,CircleHelp,ArrowLeft,FileText} from 'lucide-react';
import Brand from '@/components/brand';import ThemeToggle from '@/components/theme-toggle';import CompanyFooter from '@/components/company-footer';import {useTutorial} from '@/components/dashboard-tutorial';import {FILE_LIMIT,REPORT_CATEGORIES,fileType} from '@/lib/report-files';import {classHours} from '@/lib/class-hours';
const statuses:Record<string,string>={PENDING:'Pendiente',IN_PROGRESS:'En elaboración',IN_REVIEW:'En revisión',DELIVERED:'Entregado'};
type Person={id:string;username:string};type Doc={id:string;name:string;contentType:string;size:number;category:string;sessionDate:string|null;uploaderName:string;uploaderId:string|null;uploadedAt:string|null;state:string};
type Report={status:string;assigneeId:string|null;dueDate:string|null;deliveredAt:string|null;notes?:string;folderUrl?:string|null;finalReportUrl?:string|null;documents?:Doc[];_count?:{documents:number}};
type Service={id:string;company:string;correlativeCode:string|null;status:string;serviceDate:string;modality:string|null;course:{name:string};courses:{name:string}[];dates:{date:string;startTime:string|null;endTime:string|null}[];instructor:{name:string}|null;location:{department:string;district:string}|null;report:Report|null;reportStatus?:string};
type Data={rows:Service[];total:number;page:number;assignees:Person[];uploadsEnabled:boolean};
const date=(value:string|null)=>value?new Date(value).toLocaleDateString('es-PE',{timeZone:'UTC'}):'—';
const courses=(s:Service)=>[...new Set([s.course.name,...s.courses.map(c=>c.name)])].join(', ');
const days=(s:Service)=>s.dates.length?s.dates:[{date:s.serviceDate,startTime:null,endTime:null}];
async function api<T>(path:string,options?:RequestInit):Promise<T>{const res=await fetch(path,options);const data=await res.json();if(!res.ok)throw Error(data.error||'No se pudo completar la operación');return data;}
const json=(body:unknown,method='PATCH')=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const demo:Service={id:'tutorial-report',company:'Empresa de ejemplo',correlativeCode:'0042',status:'EXECUTED',serviceDate:'2026-10-09T09:00:00Z',modality:'IN_PERSON',course:{name:'Curso de ejemplo'},courses:[],dates:[{date:'2026-10-09T09:00:00Z',startTime:'09:00',endTime:'15:00'}],instructor:{name:'Instructor de ejemplo'},location:{department:'Lima',district:'Miraflores'},report:null};
const values=(report:Report|null)=>({status:report?.status??'PENDING',assigneeId:report?.assigneeId??'',dueDate:report?.dueDate?.slice(0,10)??'',deliveredAt:report?.deliveredAt?.slice(0,10)??'',notes:report?.notes??'',folderUrl:report?.folderUrl??'',finalReportUrl:report?.finalReportUrl??''});
export default function ReportsPanel({user}:{user:Person&{role:string}}){
 const {active:tutorial,start}=useTutorial();
 const [period,setPeriod]=useState(()=>{const p=new Intl.DateTimeFormat('en',{timeZone:'America/Lima',year:'numeric',month:'2-digit'}).formatToParts(new Date());return{year:Number(p.find(x=>x.type==='year')!.value),month:Number(p.find(x=>x.type==='month')!.value)};});
 const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[assignee,setAssignee]=useState(''),[page,setPage]=useState(1),[data,setData]=useState<Data|null>(null),[selected,setSelected]=useState<Service|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const detail=useRef<HTMLDivElement>(null),version=useRef(0);
 const load=useCallback(async()=>{const v=++version.current;setLoading(true);setError('');try{const q=new URLSearchParams({...Object.fromEntries(Object.entries(period).map(([k,v])=>[k,String(v)])),search,status,assignee,page:String(page)});const next=await api<Data>('/api/reports?'+q);if(v===version.current)setData(next);}catch(e){if(v===version.current)setError((e as Error).message);}finally{if(v===version.current)setLoading(false);}},[period,search,status,assignee,page]);
 useEffect(()=>{setSelected(null);},[period,search,status,assignee]);
 useEffect(()=>{const ref=version;void load();return()=>{ref.current++;};},[load]);
 async function open(id:string){try{setError('');setSelected(await api<Service>('/api/reports/'+id));setTimeout(()=>detail.current?.scrollIntoView({behavior:'smooth',block:'start'}),50);}catch(e){setError((e as Error).message);}}
 async function update(){if(selected)try{setSelected(await api<Service>('/api/reports/'+selected.id));}catch(e){setSelected(null);setError((e as Error).message);}await load();}
 const showingDemo=tutorial?.tab==='reports'&&tutorial.target.startsWith('.report-detail');
 return <div className="reports-shell"><aside className="reports-sidebar"><Brand href="/dashboard"/><div><span className="nav-caption">DEPARTAMENTO DE INFORMES</span><button className="nav-item active" onClick={()=>{setSelected(null);}}><ClipboardList size={19}/><span>Agenda de informes</span></button>{user.role==='ADMIN'&&<Link href="/dashboard" className="nav-item"><ArrowLeft size={19}/><span>Panel comercial</span></Link>}</div><button className="nav-item logout-button" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});window.location.assign('/login');}}><LogOut size={19}/><span>Cerrar sesión</span></button></aside>
 <main className="reports-main"><header className="topbar"><span>CONSITEC · Informes</span><div className="topbar-actions"><button className="refresh-button" data-tour="replay" onClick={start} aria-label="Ver tutorial"><CircleHelp size={18}/>Ver tutorial</button><ThemeToggle/><button className="refresh-button" data-tour="refresh" disabled={loading} onClick={()=>void update()} aria-label="Actualizar"><RefreshCw size={18}/>Actualizar</button></div></header>
 <div className="page-content"><div className="page-heading"><div><div className="eyebrow">SEGUIMIENTO Y DOCUMENTACIÓN</div><h1>Agenda de informes</h1><p>Servicios ejecutados o facturados, sin duplicar jornadas ni registros.</p></div></div>
 <section className="panel reports-agenda"><div className="reports-filters"><label>Mes<select aria-label="Mes de informes" value={period.month} onChange={e=>{setPage(1);setPeriod({...period,month:Number(e.target.value)});}}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{new Date(2026,i,1).toLocaleDateString('es-PE',{month:'long'})}</option>)}</select></label><label>Año<input aria-label="Año de informes" type="number" min="2000" max="2100" value={period.year} onChange={e=>{setPage(1);setPeriod({...period,year:Number(e.target.value)});}}/></label><label>Buscar<input aria-label="Buscar informes" placeholder="Empresa, correlativo, curso o instructor" value={search} onChange={e=>{setPage(1);setSearch(e.target.value);}}/></label><label>Estado del informe<select value={status} onChange={e=>{setPage(1);setStatus(e.target.value);}}><option value="">Todos</option>{Object.entries(statuses).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Responsable<select value={assignee} onChange={e=>{setPage(1);setAssignee(e.target.value);}}><option value="">Todos</option>{data?.assignees.map(p=><option key={p.id} value={p.id}>{p.username}</option>)}</select></label><button className="btn secondary" onClick={()=>{setSearch('');setStatus('');setAssignee('');setPage(1);}}>Limpiar</button></div>
 <p className="form-note">{data?.total??0} servicios encontrados · Cada servicio conserva una ficha para todas sus fechas.</p>{error&&<p className="error-banner" role="alert">{error}</p>}
 <div className="table-scroll"><table><thead><tr><th>Correlativo / empresa</th><th>Fechas</th><th>Instructor / cursos</th><th>Informe</th><th>Plazo</th><th>Documentos</th><th>Ficha</th></tr></thead><tbody>{data?.rows.map(s=><tr key={s.id}><td><strong>{s.correlativeCode??'Sin correlativo'}</strong><br/>{s.company}<br/><small>{s.status==='INVOICED'?'Facturado':'Ejecutado'} · {s.modality==='VIRTUAL'?'Virtual':s.modality==='IN_PERSON'?'Presencial':'Sin modalidad'}</small></td><td>{days(s).map(d=><div key={d.date}>{date(d.date)}</div>)}</td><td>{s.instructor?.name??'Sin instructor'}<br/><small>{courses(s)}</small></td><td>{statuses[s.reportStatus??'PENDING']}<br/><small>{data.assignees.find(p=>p.id===s.report?.assigneeId)?.username??'Sin responsable'}</small></td><td>{date(s.report?.dueDate??null)}</td><td>{s.report?._count?.documents??0}</td><td><button className="btn secondary" onClick={()=>void open(s.id)}>Abrir ficha</button></td></tr>)}</tbody></table></div>
 {loading&&<p role="status">Cargando agenda…</p>}{!loading&&!data?.rows.length&&<p>No hay servicios ejecutados o facturados para esta selección.</p>}<div className="history-pagination"><button className="btn secondary" disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page}</span><button className="btn secondary" disabled={loading||page*50>=(data?.total??0)} onClick={()=>setPage(p=>p+1)}>Siguiente página</button></div></section>
 {(showingDemo||selected)&&<div ref={detail}><ReportDetail key={showingDemo?'tutorial':selected!.id} service={showingDemo?demo:selected!} assignees={data?.assignees??[]} uploadsEnabled={data?.uploadsEnabled??false} user={user} demo={!!showingDemo} onDone={update} onClose={()=>setSelected(null)}/></div>}
 <CompanyFooter/></div></main></div>;
}
function ReportDetail({service:s,assignees,uploadsEnabled,user,demo:example,onDone,onClose}:{service:Service;assignees:Person[];uploadsEnabled:boolean;user:Person&{role:string};demo:boolean;onDone:()=>Promise<void>;onClose:()=>void}){

 const [form,setForm]=useState(()=>values(s.report)),[dirty,setDirty]=useState(false);
 useEffect(()=>{if(!dirty)setForm(values(s.report));},[s.report,dirty]);
 const [category,setCategory]=useState('FINAL_REPORT'),[sessionDate,setSessionDate]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[progress,setProgress]=useState<number|null>(null);const fileInput=useRef<HTMLInputElement>(null);
 const field=(key:keyof typeof form,value:string)=>{setDirty(true);setForm(old=>({...old,[key]:value}));};
 async function save(e:FormEvent){e.preventDefault();if(example||busy)return;setBusy(true);setError('');setNotice('');try{const saved=await api<Report>('/api/reports/'+s.id,json(form));setForm(old=>({...old,deliveredAt:saved.deliveredAt?.slice(0,10)??''}));await onDone();setDirty(false);setNotice('Ficha guardada.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function uploadFiles(files:FileList|null){if(!files||example||busy)return;setBusy(true);setError('');setNotice('');try{for(const file of Array.from(files)){const contentType=fileType(file.name,file.type);if(!contentType||file.size<1||file.size>FILE_LIMIT)throw Error('Usa PDF, Word, Excel, JPG, PNG o WebP de hasta 10 MB por archivo');const prepared=await api<{id:string;pathname:string}>(`/api/reports/${s.id}/documents`,json({name:file.name,size:file.size,contentType,category,sessionDate},'POST'));setProgress(0);await upload(prepared.pathname,file,{access:'private',contentType,handleUploadUrl:'/api/reports/upload',clientPayload:JSON.stringify({documentId:prepared.id}),onUploadProgress:e=>setProgress(Math.round(e.percentage))});await api(`/api/reports/${s.id}/documents/${prepared.id}`,{method:'PATCH'});}setNotice('Archivos guardados en la documentación del servicio.');}catch(e){setError((e as Error).message);}finally{setProgress(null);setBusy(false);if(fileInput.current)fileInput.current.value='';await onDone();}}
 async function documentAction(doc:Doc,method:'PATCH'|'DELETE'){if(example||busy)return;if(method==='DELETE'&&!window.confirm('¿Retirar este archivo? No se recupera desde Papelera.'))return;setBusy(true);setError('');try{await api(`/api/reports/${s.id}/documents/${doc.id}`,{method});setNotice(method==='PATCH'?'Carga completada.':'Archivo retirado.');await onDone();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel report-detail"><div className="section-heading"><div><h2>Informe · {s.correlativeCode??'Sin correlativo'} · {s.company}</h2><p>{courses(s)} · {s.instructor?.name??'Sin instructor'}</p></div><button className="text-button" disabled={busy||example} onClick={onClose}>Cerrar ficha</button></div>
 {example&&<p className="form-note">Ejemplo del tutorial: no guarda datos ni sube archivos.</p>}<div className="report-service-days">{days(s).map(d=><div key={d.date}><strong>{date(d.date)}</strong> · {d.startTime&&d.endTime?`${d.startTime}–${d.endTime} · ${((classHours(d.startTime,d.endTime)?.instructionalMinutes??0)/60).toFixed(2)} horas netas`:'Sin horario'} · {s.modality==='VIRTUAL'?'Virtual':s.modality==='IN_PERSON'?'Presencial':'Sin modalidad'} · {s.location?`${s.location.department} / ${s.location.district}`:'Sin lugar registrado'}</div>)}</div>
 {error&&<p className="error-banner" role="alert">{error}</p>}{notice&&<p className="users-notice" role="status">{notice}</p>}
 <form className="report-form" onSubmit={save}><fieldset disabled={busy||example} style={{border:0,padding:0,margin:0,minWidth:0}}><div className="form-grid"><label>Responsable<select name="reportAssignee" value={form.assigneeId} onChange={e=>field('assigneeId',e.target.value)}><option value="">Sin asignar</option>{assignees.map(p=><option key={p.id} value={p.id}>{p.username}</option>)}</select></label><label>Estado del informe<select name="reportStatus" value={form.status} onChange={e=>field('status',e.target.value)}>{Object.entries(statuses).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Fecha límite<input name="reportDueDate" type="date" value={form.dueDate} onChange={e=>field('dueDate',e.target.value)}/></label><label>Fecha de entrega<input name="reportDeliveredAt" type="date" disabled={form.status!=='DELIVERED'} value={form.deliveredAt} onChange={e=>field('deliveredAt',e.target.value)}/><small>Al entregar, se usa hoy si está vacía.</small></label><label className="full-width">Observaciones<textarea name="reportNotes" maxLength={5000} rows={4} value={form.notes} onChange={e=>field('notes',e.target.value)} placeholder="Documentación faltante o correcciones pendientes…"/></label><label>Carpeta de Drive <small>(opcional)</small><input name="reportFolderUrl" type="url" value={form.folderUrl} onChange={e=>field('folderUrl',e.target.value)} placeholder="https://drive.google.com/…"/></label><label>Enlace del informe final <small>(opcional)</small><input name="reportFinalUrl" type="url" value={form.finalReportUrl} onChange={e=>field('finalReportUrl',e.target.value)} placeholder="https://…"/></label></div><p className="form-note">El estado del informe es independiente del estado comercial. Para marcar Entregado, adjunta el informe final o su enlace. El cierre mensual comercial no bloquea este trabajo.</p><div className="dialog-actions"><button className="btn" disabled={busy||example}>{busy?'Guardando…':'Guardar ficha'}</button></div></fieldset>{dirty&&<p className="form-note">Tienes cambios sin guardar en la ficha.</p>}</form>
 {(s.report?.folderUrl||s.report?.finalReportUrl)&&<div className="report-links">{s.report.folderUrl&&<a className="btn secondary" href={s.report.folderUrl} target="_blank" rel="noopener noreferrer">Abrir carpeta</a>}{s.report.finalReportUrl&&<a className="btn secondary" href={s.report.finalReportUrl} target="_blank" rel="noopener noreferrer">Abrir informe final</a>}</div>}
 <section className="report-documentation"><div className="section-heading"><div><h2>Documentación</h2><p>Archivos privados · PDF, Word, Excel e imágenes · hasta 10 MB por archivo</p></div><FileText size={20}/></div><div className="form-grid"><label>Categoría<select name="documentCategory" value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(REPORT_CATEGORIES).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Jornada<select name="documentSession" value={sessionDate} onChange={e=>setSessionDate(e.target.value)}><option value="">General del servicio</option>{days(s).map(d=><option key={d.date} value={d.date.slice(0,10)}>{date(d.date)}</option>)}</select></label><label className="full-width">Subir archivos<input ref={fileInput} type="file" name="reportFiles" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png,.webp" disabled={busy||example||!uploadsEnabled} onChange={e=>void uploadFiles(e.target.files)}/></label></div>{!uploadsEnabled&&<p className="form-note">El almacenamiento aún no está configurado.</p>}{progress!==null&&<p role="status">Subiendo… {progress}%</p>}
 <ul className="report-documents">{s.report?.documents?.map(doc=><li key={doc.id}><div><strong>{doc.name}</strong><small>{REPORT_CATEGORIES[doc.category]} · {doc.sessionDate?date(doc.sessionDate):'General'} · {(doc.size/1024/1024).toFixed(2)} MB</small><small>{doc.uploaderName} · {date(doc.uploadedAt)}{doc.state==='PENDING'?' · Carga sin completar':''}</small></div><div className="report-file-actions">{doc.state==='READY'?<><a href={`/api/reports/documents/${doc.id}`} target="_blank" rel="noopener noreferrer">Abrir</a><a href={`/api/reports/documents/${doc.id}?download=1`}>Descargar</a></>:doc.uploaderId===user.id&&<button className="text-button" disabled={busy||example} onClick={()=>void documentAction(doc,'PATCH')}>Finalizar carga</button>}{(doc.uploaderId===user.id||user.role==='ADMIN')&&<button className="text-button" disabled={busy||example} onClick={()=>void documentAction(doc,'DELETE')}>Retirar</button>}</div></li>)}</ul>{!s.report?.documents?.length&&<p className="form-note">Todavía no hay archivos adjuntos.</p>}</section>
 </section>;
}
