import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {PrismaClient} from '@prisma/client';import bcrypt from 'bcrypt';import {put} from '@vercel/blob/client';import {del} from '@vercel/blob';
assert(['localhost','127.0.0.1'].includes(new URL(process.env.DATABASE_URL).hostname),'Local test database only');const db=new PrismaClient(),tag='quotes-'+randomUUID(),password=randomUUID(),base=process.env.SMOKE_BASE_URL||'http://127.0.0.1:3060';const users=[],reps=[],courses=[],paths=[];let checks=0;
async function call(path,cookie,method='GET',body){checks++;const r=await fetch(base+path,{method,redirect:'manual',headers:{...(cookie?{cookie}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return r;}
async function data(r,status=200){assert.equal(r.status,status,await r.clone().text());return r.json();}
async function login(role,rep){const user=await db.user.create({data:{username:tag+users.length,password:await bcrypt.hash(password,10),role,salespersonId:rep?.id,tutorialCompleted:true}});users.push(user.id);const r=await call('/api/auth/login',null,'POST',{username:user.username,password});await data(r);return r.headers.get('set-cookie').split(';')[0];}
try{
 for(let i=0;i<2;i++){reps.push(await db.salesperson.create({data:{name:tag+i}}));courses.push(await db.course.create({data:{name:tag+i}}));}
 const admin=await login('ADMIN'),sales=await login('SALES',reps[0]),other=await login('SALES',reps[1]);
 await data(await call('/api/quotations'),401);const before=await data(await call('/api/dashboard?month=11&year=2096',sales));
 const body={company:tag,contact:'Cliente ejemplo',participants:20,amount:'2500.50',modality:'VIRTUAL',status:'DRAFT',courseIds:courses.map(c=>c.id),tentativeDates:['2096-11-01','2096-11-02'],validUntil:'2096-11-30',followUpDate:'2096-10-31',conditions:'Pago acordado',notes:'Primera propuesta',salespersonId:reps[1].id};
 await data(await call('/api/quotations',admin,'POST',body),409);
 for(const bad of [{amount:0},{amount:'12.123'},{participants:-1},{validUntil:'2026-02-30'},{tentativeDates:['2026-02-30']},{status:'PAID'},{courseIds:[]}])await data(await call('/api/quotations',sales,'POST',{...body,...bad}),400);
 const quote=await data(await call('/api/quotations',sales,'POST',body),201);assert.equal(quote.salespersonId,reps[0].id);assert.equal(quote.courses.length,2);await data(await call(`/api/metadata/courses/${courses[0].id}`,admin,'DELETE'),400);assert.equal((await data(await call('/api/quotations',other))).rows.filter(q=>q.id===quote.id).length,0);assert((await data(await call('/api/quotations',admin))).rows.some(q=>q.id===quote.id));
 await data(await call(`/api/quotations/${quote.id}`,other,'PATCH',body),404);await data(await call(`/api/quotations/${quote.id}/convert`,other,'POST',{}),404);
 const unchanged=await data(await call('/api/dashboard?month=11&year=2096',sales));assert.equal(before.totalServices,unchanged.totalServices);assert.equal(before.totalInvoicedBilling,unchanged.totalInvoicedBilling);
 const service={correlativeCode:'9921',sessions:[{date:'2096-11-01',startTime:'09:00',endTime:'15:00'},{date:'2096-11-02',startTime:'08:00',endTime:'12:00'}],instructorId:null,locationId:null,travelMode:'NONE',company:'Tampered',amount:1,salespersonId:reps[1].id,courseIds:[courses[1].id],status:'INVOICED',certificatesOnly:true};
 await data(await call(`/api/quotations/${quote.id}/convert`,sales,'POST',service),409);
 const expired=await data(await call('/api/quotations',sales,'POST',{...body,company:tag+' expired',status:'SENT',validUntil:'2000-01-01'}),201);assert.equal(expired.effectiveStatus,'EXPIRED');
 await data(await call(`/api/quotations/${quote.id}`,sales,'PATCH',{...body,status:'ACCEPTED'}));
 // Concurrency must generate exactly one service; user supplied commercial values are ignored.
 const converted=await Promise.all([call(`/api/quotations/${quote.id}/convert`,sales,'POST',service),call(`/api/quotations/${quote.id}/convert`,sales,'POST',service)]);const [a,b]=await Promise.all(converted.map(r=>data(r)));assert.equal(a.id,b.id);assert.equal(a.company,tag);assert.equal(a.amount,'2500.5');assert.equal(a.salespersonId,reps[0].id);assert.equal(a.status,'SCHEDULED');assert.equal(a.certificatesOnly,false);assert.equal(a.courses.length,2);assert.equal(a.dates.length,2);
 await data(await call(`/api/quotations/${quote.id}`,sales,'PATCH',body),409);const total=await data(await call('/api/dashboard?month=11&year=2096',sales));assert.equal(total.totalServices,before.totalServices+2);assert.equal(total.totalInvoicedBilling,before.totalInvoicedBilling);
 const documentPath=`/api/quotations/${quote.id}/documents`;
 for(const invalid of [{name:'bad.doc',size:10,contentType:'application/msword'},{name:'large.pdf',size:10485761,contentType:'application/pdf'},{name:'zero.pdf',size:0,contentType:'application/pdf'}])await data(await call(documentPath,sales,'POST',invalid),400);
 const bytes=Buffer.from('%PDF-1.4\n% Private quotation smoke\n%%EOF\n');const doc=await data(await call(documentPath,sales,'POST',{name:'Cotizacion.pdf',size:bytes.length,contentType:'application/pdf'}),201);paths.push(doc.pathname);
 const tokenBody={type:'blob.generate-client-token',payload:{pathname:doc.pathname,clientPayload:JSON.stringify({documentId:doc.id}),multipart:false}};await data(await call('/api/quotations/upload',other,'POST',tokenBody),403);await data(await call('/api/quotations/upload',sales,'POST',{...tokenBody,payload:{...tokenBody.payload,pathname:'quotations/other.pdf'}}),403);
 const token=await data(await call('/api/quotations/upload',sales,'POST',tokenBody));const blob=await put(doc.pathname,new Blob([bytes],{type:'application/pdf'}),{access:'private',contentType:'application/pdf',token:token.clientToken});assert([401,403,404].includes((await fetch(blob.url)).status));
 const filePath=`${documentPath}/${doc.id}`;await data(await call(filePath,other,'PATCH',{}),404);await data(await call(filePath,sales,'PATCH',{}));await data(await call(filePath,sales,'PATCH',{}));await data(await call(filePath,other),404);await data(await call(filePath),401);const download=await call(filePath+'?download=1',sales);assert.equal(download.status,200);assert.match(download.headers.get('content-disposition'),/^attachment/);assert.deepEqual(Buffer.from(await download.arrayBuffer()),bytes);assert.equal((await call(filePath,admin)).status,200);
 assert((await data(await call('/api/quotations',sales))).rows.find(q=>q.id===quote.id).documents.every(d=>!d.pathname));
 // Permanently deleting a service preserves the conversion marker and cannot create a second sale.
 await db.service.delete({where:{id:a.id}});assert((await db.quotation.findUnique({where:{id:quote.id}})).convertedAt);await data(await call(`/api/quotations/${quote.id}/convert`,sales,'POST',service),409);
 assert(await db.auditLog.count({where:{actorId:{in:users},entity:'QUOTATION'}})>2);
 console.log(`Quotations smoke passed: ${checks} requests; owner isolation, validation, expiry, no quotation billing, concurrent single conversion, preserved commercial data, private PDF upload/download and irreversible conversion marker.`);
}finally{for(const pathname of paths)await del(pathname).catch(()=>{});await db.quotation.deleteMany({where:{salespersonId:{in:reps.map(r=>r.id)}}});await db.service.deleteMany({where:{salespersonId:{in:reps.map(r=>r.id)}}});await db.auditLog.deleteMany({where:{actorId:{in:users}}});await db.user.deleteMany({where:{id:{in:users}}});await db.course.deleteMany({where:{id:{in:courses.map(c=>c.id)}}});await db.salesperson.deleteMany({where:{id:{in:reps.map(r=>r.id)}}});await db.$disconnect();}
