import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {parseEnv} from 'node:util';import {PrismaClient} from '@prisma/client';import bcrypt from 'bcrypt';import {randomUUID} from 'node:crypto';import {put} from '@vercel/blob/client';import {del} from '@vercel/blob';
const vars=parseEnv(readFileSync('.env','utf8'));assert(['localhost','127.0.0.1'].includes(new URL(vars.DATABASE_URL).hostname));assert.equal(new URL(vars.DATABASE_URL).pathname,'/consitec');Object.assign(process.env,{BLOB_READ_WRITE_TOKEN:vars.BLOB_READ_WRITE_TOKEN});
const base=process.env.SMOKE_BASE_URL||'http://127.0.0.1:3048';assert(['localhost','127.0.0.1'].includes(new URL(base).hostname));const db=new PrismaClient({datasources:{db:{url:vars.DATABASE_URL}}}),tag='reports-'+randomUUID(),password=randomUUID()+randomUUID(),ids=[],paths=[];let course,rep,requests=0;
async function call(path,method='GET',body,cookie){requests++;const r=await fetch(base+path,{method,redirect:'manual',headers:{...(cookie?{Cookie:cookie}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});let data;try{data=await r.clone().json();}catch{}return{status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],response:r};}
try{
 course=await db.course.create({data:{name:tag}});rep=await db.salesperson.create({data:{name:tag}});let admin,sales,reports,other;
 for(const role of ['ADMIN','SALES','REPORTS','REPORTS']){const user=await db.user.create({data:{username:tag+ids.length,password:await bcrypt.hash(password,10),role,salespersonId:role==='REPORTS'?null:rep.id,tutorialCompleted:true}});ids.push(user.id);const login=await call('/api/auth/login','POST',{username:user.username,password});assert.equal(login.status,200);if(role==='ADMIN')admin=login.cookie;else if(role==='SALES')sales=login.cookie;else if(!reports)reports=login.cookie;else other=login.cookie;}
 const created=await call('/api/users','POST',{email:tag+'@example.com',password,role:'REPORTS'},admin);assert.equal(created.status,201);assert.equal(created.data.salespersonId,null);ids.push(created.data.id);
 assert.equal((await call('/api/users','PATCH',{id:created.data.id,salespersonId:rep.id},admin)).status,400);
 assert.equal((await call('/api/reports')).status,401);assert.equal((await call('/api/reports','GET',undefined,sales)).status,403);
 for(const path of ['/api/services','/api/dashboard','/api/users','/api/history','/api/metadata/salespeople','/api/monthly-close'])assert.equal((await call(path,'GET',undefined,reports)).status,403,path);
 const redirected=await call('/dashboard','GET',undefined,reports);assert.equal(redirected.status,307);assert.match(redirected.response.headers.get('location'),/dashboard\/reports$/);
 const common={courseId:course.id,salespersonId:rep.id,company:tag,amount:150,correlativeCode:'0042',modality:'VIRTUAL',serviceDate:new Date('2042-04-10T09:00:00Z')};
 const s=await db.service.create({data:{...common,status:'EXECUTED',dates:{create:[{date:new Date('2042-04-10T09:00:00Z'),startTime:'09:00',endTime:'15:00'},{date:new Date('2042-04-11T09:00:00Z'),startTime:'09:00',endTime:'13:00'}]}}});
 const scheduled=await db.service.create({data:{...common,company:tag+'scheduled',status:'SCHEDULED'}});await db.service.create({data:{...common,company:tag+'copy',certificatesOnly:true,status:'INVOICED'}});await db.service.create({data:{...common,company:tag+'trash',status:'EXECUTED',deletedAt:new Date()}});
 const list=()=>call('/api/reports?year=2042&month=4&search='+encodeURIComponent(tag),'GET',undefined,reports);
 let agenda=await list();assert.equal(agenda.status,200);assert.equal(agenda.data.rows.length,1);assert.equal(agenda.data.rows[0].id,s.id);assert.equal(agenda.data.rows[0].dates.length,2);assert.equal(agenda.data.rows[0].reportStatus,'PENDING');assert(!('amount' in agenda.data.rows[0]));
 assert.equal((await call('/api/reports/'+scheduled.id,'GET',undefined,reports)).status,404);
 const form={status:'IN_PROGRESS',assigneeId:ids[2],notes:'Falta asistencia de la segunda jornada',dueDate:'2042-04-20',deliveredAt:'',folderUrl:'https://drive.google.com/drive/folders/example',finalReportUrl:''};
 assert.equal((await call('/api/reports/'+s.id,'PATCH',form,reports)).status,200);const firstId=(await db.serviceReport.findUnique({where:{serviceId:s.id}})).id;
 await db.service.update({where:{id:s.id},data:{status:'INVOICED',invoicedAt:new Date('2042-04-12T09:00:00Z')}});agenda=await list();assert.equal(agenda.data.rows.length,1);assert.equal(agenda.data.rows[0].reportStatus,'IN_PROGRESS');assert.equal((await db.serviceReport.findUnique({where:{serviceId:s.id}})).id,firstId);
 assert.equal((await call('/api/reports/'+s.id,'PATCH',{...form,status:'DELIVERED'},reports)).status,400);assert.equal((await call('/api/reports/'+s.id,'PATCH',{...form,folderUrl:'javascript:alert(1)'},reports)).status,400);assert.equal((await call('/api/reports/'+s.id,'PATCH',{...form,assigneeId:ids[1]},reports)).status,400);
 const bytes=new TextEncoder().encode('%PDF-1.4\n% Informe de prueba CONSITEC\n%%EOF\n');const prepareBody={name:'informe-prueba.pdf',contentType:'application/pdf',size:bytes.length,category:'FINAL_REPORT',sessionDate:'2042-04-11'};
 assert.equal((await call(`/api/reports/${s.id}/documents`,'POST',{...prepareBody,size:11*1024*1024},reports)).status,400);assert.equal((await call(`/api/reports/${s.id}/documents`,'POST',{...prepareBody,sessionDate:'2042-04-12'},reports)).status,400);assert.equal((await call(`/api/reports/${s.id}/documents`,'POST',{...prepareBody,name:'bad.svg',contentType:'image/svg+xml'},reports)).status,400);
 const prepared=await call(`/api/reports/${s.id}/documents`,'POST',prepareBody,reports);assert.equal(prepared.status,201);paths.push(prepared.data.pathname);
 const tokenBody={type:'blob.generate-client-token',payload:{pathname:prepared.data.pathname,clientPayload:JSON.stringify({documentId:prepared.data.id}),multipart:false}};
 assert.equal((await call('/api/reports/upload','POST',tokenBody,other)).status,403);assert.equal((await call('/api/reports/upload','POST',{...tokenBody,payload:{...tokenBody.payload,pathname:'reports/other/path.pdf'}},reports)).status,403);
 const token=await call('/api/reports/upload','POST',tokenBody,reports);assert.equal(token.status,200);
 const blob=await put(prepared.data.pathname,new Blob([bytes],{type:'application/pdf'}),{access:'private',contentType:'application/pdf',token:token.data.clientToken});
 const publicGet=await fetch(blob.url);assert([401,403,404].includes(publicGet.status),'Private files must not be publicly readable');
 assert.equal((await call(`/api/reports/${s.id}/documents/${prepared.data.id}`,'PATCH',undefined,other)).status,404);assert.equal((await call(`/api/reports/${s.id}/documents/${prepared.data.id}`,'PATCH',undefined,reports)).status,200);assert.equal((await call(`/api/reports/${s.id}/documents/${prepared.data.id}`,'PATCH',undefined,reports)).status,200);
 const download=await call('/api/reports/documents/'+prepared.data.id+'?download=1','GET',undefined,reports);assert.equal(download.status,200);assert.deepEqual(new Uint8Array(await download.response.arrayBuffer()),bytes);assert.match(download.response.headers.get('content-disposition'),/attachment/);assert.equal((await call('/api/reports/documents/'+prepared.data.id,'GET',undefined,sales)).status,403);assert.equal((await call('/api/reports/documents/'+prepared.data.id)).status,401);
 assert.equal((await call('/api/reports/'+s.id,'PATCH',{...form,status:'DELIVERED',deliveredAt:'2042-04-21'},reports)).status,200);assert.equal((await call(`/api/reports/${s.id}/documents/${prepared.data.id}`,'DELETE',undefined,reports)).status,400);
 await db.service.update({where:{id:s.id},data:{deletedAt:new Date()}});assert.equal((await list()).data.rows.length,0);assert.equal((await call('/api/reports/documents/'+prepared.data.id,'GET',undefined,reports)).status,404);await db.service.update({where:{id:s.id},data:{deletedAt:null,status:'SCHEDULED'}});assert.equal((await list()).data.rows.length,0);await db.service.update({where:{id:s.id},data:{status:'EXECUTED'}});assert.equal((await list()).data.rows[0].reportStatus,'DELIVERED');
 assert.equal((await call('/api/reports/'+s.id,'PATCH',form,reports)).status,200);assert.equal((await call(`/api/reports/${s.id}/documents/${prepared.data.id}`,'DELETE',undefined,other)).status,403);assert.equal((await call(`/api/reports/${s.id}/documents/${prepared.data.id}`,'DELETE',undefined,reports)).status,200);assert.equal((await call('/api/reports/documents/'+prepared.data.id,'GET',undefined,reports)).status,404);
 assert(await db.auditLog.count({where:{actorId:ids[2],entity:'REPORT_DOCUMENT',action:'CREATE'}}));assert(await db.auditLog.count({where:{actorId:ids[2],entity:'REPORT',action:'UPDATE'}}));assert.equal((await db.service.findUnique({where:{id:s.id}})).amount.toString(),'150');
 console.log(`PASS: reports (${requests} requests): role isolation/no commercial, automatic agenda, multi-date/no duplicates, workflow, actual private client upload/download, authorization, file validation, audit and unchanged commercial amount.`);
}finally{if(paths.length)await del(paths);await db.reportDocument.deleteMany({where:{uploaderId:{in:ids}}});if(rep)await db.service.deleteMany({where:{salespersonId:rep.id}});await db.auditLog.deleteMany({where:{actorId:{in:ids}}});await db.user.deleteMany({where:{id:{in:ids}}});if(course)await db.course.delete({where:{id:course.id}});if(rep)await db.salesperson.delete({where:{id:rep.id}});await db.$disconnect();}
